### ISSUE TITLE
Create Kanban board for Space Travelers' Hub Project

### ISSUE THREAD

**Issue by shihabrafio** [shihabrafio/Space-Hub#25]
We are Three people here (Rafio, Yousef & Vangelis)
Here is the link to our [GitHub project](https://github.com/shihabrafio/Space-Hub/projects/1)

**Comment by andersonlebon** [comment]
## Hi @ybadr99 team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
